version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-bakong
    ports:
      - "4001:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: always
